from pathlib import Path

path = Path("src/autotrade/health_bridge.py")
text = path.read_text()
old = '''def _state_from_row(row: sqlite3.Row) -> HealthBridgeState:\n    try:\n        state = HealthBridgeState(\n            entity_id=str(row["entity_id"]),\n            entity_kind=HealthEntityKind(str(row["entity_kind"])),\n            mode=HealthRiskMode(str(row["mode"])),\n            risk_multiplier=Decimal(str(row["risk_multiplier"])),\n            health_state_version=int(row["health_state_version"]),\n            health_state_fingerprint=str(row["health_state_fingerprint"]),\n            baseline_fingerprint=str(row["baseline_fingerprint"]),\n            policy_fingerprint=str(row["policy_fingerprint"]),\n            bridge_version=int(row["bridge_version"]),\n            updated_at=datetime.fromisoformat(str(row["updated_at"])),\n        )\n    except (InvalidOperation, TypeError, ValueError) as exc:\n        raise HealthBridgeConflict("stored health bridge state is invalid") from exc\n    stored_hash = row["state_hash"]\n    if not isinstance(stored_hash, str) or not _SHA256_RE.fullmatch(stored_hash):\n        raise HealthBridgeConflict("stored health bridge state hash is invalid")\n    if state.fingerprint != stored_hash:\n        raise HealthBridgeConflict("stored health bridge state hash mismatch")\n    return state\n'''
new = '''def _state_from_row(row: sqlite3.Row) -> HealthBridgeState:\n    stored_hash = row["state_hash"]\n    if not isinstance(stored_hash, str) or not _SHA256_RE.fullmatch(stored_hash):\n        raise HealthBridgeConflict("stored health bridge state hash is invalid")\n\n    # Verify the commitment over the raw persisted representation before\n    # semantic parsing. This distinguishes simple row tamper from a row whose\n    # attacker also recomputed the commitment; the latter is then rejected by\n    # HealthBridgeState semantic invariants below.\n    try:\n        raw_fingerprint = _hash(\n            {\n                "entity_id": str(row["entity_id"]),\n                "entity_kind": str(row["entity_kind"]),\n                "mode": str(row["mode"]),\n                "risk_multiplier": str(row["risk_multiplier"]),\n                "health_state_version": int(row["health_state_version"]),\n                "health_state_fingerprint": str(row["health_state_fingerprint"]),\n                "baseline_fingerprint": str(row["baseline_fingerprint"]),\n                "policy_fingerprint": str(row["policy_fingerprint"]),\n                "bridge_version": int(row["bridge_version"]),\n                "updated_at": str(row["updated_at"]),\n            }\n        )\n    except (TypeError, ValueError) as exc:\n        raise HealthBridgeConflict("stored health bridge state is invalid") from exc\n    if raw_fingerprint != stored_hash:\n        raise HealthBridgeConflict("stored health bridge state hash mismatch")\n\n    try:\n        state = HealthBridgeState(\n            entity_id=str(row["entity_id"]),\n            entity_kind=HealthEntityKind(str(row["entity_kind"])),\n            mode=HealthRiskMode(str(row["mode"])),\n            risk_multiplier=Decimal(str(row["risk_multiplier"])),\n            health_state_version=int(row["health_state_version"]),\n            health_state_fingerprint=str(row["health_state_fingerprint"]),\n            baseline_fingerprint=str(row["baseline_fingerprint"]),\n            policy_fingerprint=str(row["policy_fingerprint"]),\n            bridge_version=int(row["bridge_version"]),\n            updated_at=datetime.fromisoformat(str(row["updated_at"])),\n        )\n    except (InvalidOperation, TypeError, ValueError) as exc:\n        raise HealthBridgeConflict("stored health bridge state is invalid") from exc\n    return state\n'''
if old not in text:
    raise SystemExit("health bridge state parser block not found")
path.write_text(text.replace(old, new, 1))
